### ISSUE TITLE
请问，如果是在windows10下用不了会不会是分辨率的问题呢？

### ISSUE THREAD

**Issue by AshZh** [ArtrixTech/BoomMine#1]
您好，我在windows10下面用不了，选区的大小明显的太小了。完全不能够覆盖扫雷的窗体。而且似乎并没有办法自动定位。

**Comment by ArtrixTech** [comment]
使用的是原版扫雷还是Minesweeper Arbiter呢？目前只支持MS-Arbiter哦

**Comment by BlankAix** [comment]
表示新手正在看代码。觉得那个mouseOperation.py的SW，SH有可能影响到？

**Comment by ArtrixTech** [comment]
@BlankAix 不可能的，mouseoperation是一个封装好的文件，你看名字也知道只负责鼠标的操控，issue的问题在没法拿到窗口句柄，应该是没有按照文章说的来使用msarbiter而是用了别的版本的扫雷了

**Comment by scliubit** [comment]
您好，这个问题应该是显示设置里面设置成非100%造成的。遇到相同的问题，已经解决。
